dev: true
service:
  type: NodePort
  ports:
    http_port: 30941
    debug_port: 30942
deployment:
  replicas: 1
  strategy: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 100Mi
      cpu: 100m
apps:
  port: 8001
  broker_host: kafka-broker
  broker_port: 9092
  topic_name: tweety
  consumer_group: tweet_squad
  elastic_host: elasticsearch-master
  elastic_port: 9200
  indice: tweet-kafka
  indice_type: tweets
  rest_consume: /consume
image: samutup/kafka-twitter-consumer:1.0.0